### ISSUE TITLE
configure probes

### ISSUE THREAD

**Issue by cppforlife** [cppforlife/knctl#34]
consider how to configure probes when deploying

```
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
```
