### ISSUE TITLE
configure volumes with secrets/config-maps

### ISSUE THREAD

**Issue by cppforlife** [cppforlife/knctl#35]
```
container:
  volumeMounts:
  - name: db-credentials
    mountPath: "/secrets/db-credentials"
    readOnly: true
volumes:
- name: db-credentials
  secret:
    secretName: db-secret
```

```
knctl deploy --vol-secret db-credentials=db-secret:/secrets/db-credentials
knctl deploy --vol-secret db-credentials=db-secret:/secrets/db-credentials:ro
knctl deploy --vol-secret db-credentials:/secrets/db-credentials
```
